name: Python_pipeline

on:
  push:
    branches:
      - main

jobs:
  checkstyle_project:
#    needs: name_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Check style project
#        continue-on-error: true
        run: |
          npm install jsdom
          jsdom .
